{% set name = "gdb" %}
{% set version = "10.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://ftp.gnu.org/gnu/gdb/gdb-{{ version }}.tar.xz
  sha256: aaa1223d534c9b700a8bec952d9748ee1977513f178727e1bee520ee000b4f29
  patches:
    - 0001-darwin-nat.c-do-not-hang-on-long-gone-thread.patch

build:
  number: 3
  skip: True  # [win]
  # needed by macOS codesigning script
  script_env:
   - TMPDIR

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make >=3.82
    - gnuconfig   # [unix]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - ncurses
    - texinfo
    - xz
    - zlib
    - readline
    - libiconv  # [osx]
    - expat     # [osx]
  run:
    - python
    - ncurses
    - xz
    - zlib
    - six
    - libiconv  # [osx]
    - expat     # [osx]

test:
  commands:
    - gdb --version
  requires:
    - {{ compiler('c') }}

about:
  home: https://www.gnu.org/software/gdb/
  license: GPL-3.0-only
  license_family: GPL
  license_file: gdb/COPYING
  summary: GDB, the GNU Project debugger, allows you to see what is going on inside another program while it executes -- or what another program was doing at the moment it crashed.
  description: |
    GDB, the GNU Project debugger, allows you to see what is going on `inside'
    another program while it executes -- or what another program was doing at
    the moment it crashed.
    The program being debugged can be written in Ada, C, C++, Objective-C,
    Pascal (and many other languages). Those programs might be executing on the
    same machine as GDB (native) or on another machine (remote).
    GDB can run on most popular UNIX and Microsoft Windows variants.
  doc_url: https://sourceware.org/gdb/current/onlinedocs/gdb/
  dev_url: git://sourceware.org/git/binutils-gdb.git

extra:
  recipe-maintainers:
    - gqmelo
    - marcelotrevisani
    - phil-blain
