{% set name = "gdb" %}
{% set version = "17.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url:
    - https://ftp.gnu.org/gnu/gdb/gdb-{{ version }}.tar.xz
    - https://mirrors.ocf.berkeley.edu/gnu/gdb/gdb-{{ version }}.tar.xz
  sha256: 14996f5f74c9f68f5a543fdc45bca7800207f91f92aeea6c2e791822c7c6d876
  patches:
    - 0003-darwin-nat.c-Add-missing-include.patch

build:
  number: 0
  skip: true  # [win]
  # needed by macOS codesigning script
  script_env:
    - TMPDIR

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - gnuconfig  # [unix]
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make >=3.82
    - pkg-config
  host:
    - python
    - ncurses
    - texinfo
    - liblzma-devel
    - zlib
    - readline
    - libiconv
    - expat     # [osx]
    - gmp
    - mpfr
    - zstd
  run:
    - python
    - ncurses
    - liblzma-devel
    - zlib
    - zstd
    - six
    - libiconv
    - expat     # [osx]
    - pygments

test:
  commands:
    - $PREFIX/bin/gdb --version
    - $PREFIX/bin/gdb -q -ex "show host-charset" --batch
  requires:
    - {{ compiler('c') }}
    - mold

about:
  home: https://www.gnu.org/software/gdb/
  license: GPL-3.0-only
  license_family: GPL
  license_file: gdb/COPYING
  summary: GDB, the GNU Project debugger, allows you to see what is going on inside another program while it executes -- or what another program was doing at the moment it crashed.
  description: |
    GDB, the GNU Project debugger, allows you to see what is going on `inside'
    another program while it executes -- or what another program was doing at
    the moment it crashed.
    The program being debugged can be written in Ada, C, C++, Objective-C,
    Pascal (and many other languages). Those programs might be executing on the
    same machine as GDB (native) or on another machine (remote).
    GDB can run on most popular UNIX and Microsoft Windows variants.
  doc_url: https://sourceware.org/gdb/current/onlinedocs/gdb/
  dev_url: https://sourceware.org/git/binutils-gdb.git

extra:
  recipe-maintainers:
    - gqmelo
    - marcelotrevisani
    - phil-blain
    - matthiasdiener
    - jmakovicka
