{% set name = "gdb" %}
{% set version = "7.12.1" %}
{% set sha256 = "4607680b973d3ec92c30ad029f1b7dbde3876869e6b3a117d8a7e90081113186" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: gdb-{{ version }}.tar.xz
  url: http://ftp.gnu.org/gnu/gdb/gdb-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win or osx]

requirements:
  build:
    - python
    - ncurses 5.9*
    - texinfo
    - toolchain
    - xz 5.2.*
  run:
    - python
    - ncurses 5.9*
    - xz 5.2.*

test:
  commands:
    - gdb --version

about:
  home: https://www.gnu.org/software/gdb/
  license: GPL
  license_file: COPYING
  summary: GDB, the GNU Project debugger, allows you to see what is going on inside another program while it executes -- or what another program was doing at the moment it crashed.

  description: |
    GDB, the GNU Project debugger, allows you to see what is going on `inside'
    another program while it executes -- or what another program was doing at
    the moment it crashed.
    The program being debugged can be written in Ada, C, C++, Objective-C,
    Pascal (and many other languages). Those programs might be executing on the
    same machine as GDB (native) or on another machine (remote).
    GDB can run on most popular UNIX and Microsoft Windows variants.
  doc_url: https://sourceware.org/gdb/current/onlinedocs/gdb/
  dev_url: git://sourceware.org/git/binutils-gdb.git

extra:
  recipe-maintainers:
    - gqmelo
