schema_version: 1

context:
  name: gdb
  version: "17.2"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url:
    - https://ftp.gnu.org/gnu/gdb/gdb-${{ version }}.tar.xz
    - https://mirrors.ocf.berkeley.edu/gnu/gdb/gdb-${{ version }}.tar.xz
  sha256: 1c036c0d72e4b3d1fb5c94c88632add6f9d76f4d7c4d2ea793c12a9f19a3228c
  patches:
    - 0003-darwin-nat.c-Add-missing-include.patch

build:
  # needed by macOS codesigning script
  number: 2
  skip: win or target_platform == "osx-arm64"
  script:
    secrets:
      - TMPDIR

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - if: unix
      then: gnuconfig
    - ${{ compiler('fortran') }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - make >=3.82
    - pkg-config
  host:
    - python
    - libpython
    - ncurses
    - texinfo
    - liblzma-devel
    - zlib
    - readline
    - libiconv
    - if: osx
      then: expat
    - gmp
    - mpfr
    - zstd
  run:
    - python
    - libpython
    - ncurses
    - liblzma-devel
    - zlib
    - zstd
    - six
    - libiconv
    - if: osx
      then: expat
    - pygments

tests:
  - requirements:
      run:
        - ${{ compiler('c') }}
        - mold
    script:
      - $PREFIX/bin/gdb --version
      - $PREFIX/bin/gdb -q -ex "show host-charset" --batch

about:
  license: GPL-3.0-only
  license_file: gdb/COPYING
  summary: GDB, the GNU Project debugger, allows you to see what is going on inside another program while it executes -- or what another program was doing at the moment it crashed.
  description: |
    GDB, the GNU Project debugger, allows you to see what is going on `inside'
    another program while it executes -- or what another program was doing at
    the moment it crashed.
    The program being debugged can be written in Ada, C, C++, Objective-C,
    Pascal (and many other languages). Those programs might be executing on the
    same machine as GDB (native) or on another machine (remote).
    GDB can run on most popular UNIX and Microsoft Windows variants.
  homepage: https://www.gnu.org/software/gdb/
  repository: https://sourceware.org/git/binutils-gdb.git
  documentation: https://sourceware.org/gdb/current/onlinedocs/gdb/

extra:
  recipe-maintainers:
    - gqmelo
    - marcelotrevisani
    - phil-blain
    - matthiasdiener
    - jmakovicka
