appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: wuJaSX/imX8Xf5Gp1H/tFmqrx1rsNrvpUf/1SzCFku7pU1YgwzVVktUMy64APFaIGLywNyBCSeU/7wEujjutJk5SZJ3wURQusPnNZ7pbsOPFpLnbTCtLdFyXj2c/hy9cBN6elkwt+2YyIMUJJtsTlMjp0rUfw8Uq8jgk3MHChr0Jfxj7kenQeXLcpXZseCs2ucvBKIHtwp19kY95CkQ99VXfFD1lDV92SqwPuYbF0FVIMFixTHmoSPTdFbGR3HR0oGC4fXO6GiK8WjtibETq2etIaL1RaJee3ZQOpZi0F6dI05663YsEqkmnSK5e0rimLuDAzve6kBMq6SlZV20L2/Vljw0qcNr/qpAp3pb5hEP/g8dHA9jE0qq339V/XxE9we3IaRmdcX5Gou6DWE6vlen6L4WQxoJWjiwVg0viD0A8RZnIb91M9IPfM4WgHpTLpNJeWHgDul/sQROzwfk2hO97trXNu0BsUkdQXzqRxSg7p8w2Yj8v3Rar+TmAHYrj/O01vM2b01dteRZS2zZLHW+VePLB954hH57hyQ1JJw9b2y6zVxoPM8e2HotdivdIOvqLyZTIhmmJjeFyynmKwNSy2BYXzqdY8ZBnB9lxi+ELan71uD6A1AmOOx64x519VqFUTGpXH0sadstq/omBqQC9nbyQag0bJYR51tERC14=}
